main: main.c Fable.Tests.C.fs.c
	gcc -g main.c -o main
main.exe: main.c Fable.Tests.C.fs.c
	gcc -g main.c -o main.exe
arrays.exe: arrays_testing.c
	gcc -g arrays_testing.c -o arrays.exe
all: main.exe main arrays.exe